---
title: "r期末测试"
author: "Auzzer_Pang"
date: "6/19/2020"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
par(family='STKaiti')
rm (list = ls())
x1 = 1; x2 = 2;
```

```{r}
#test
x = rnorm(100,2,9)
# as.vector(x)
library(dplyr)
# as.numeric(x)
y1 = NULL
for (i in 1:length(x)){
  if (x[i]>5&x[i]<10 )
    y1 = cbind(y1,i)
}
y1

```

```{r}
a = c(1,1)
plot(a,lwd = 2)


```

```{r}
R_testf <-function(x){
  if(1<x & x<5){y = 2*x^2+1}
  if(x<=1|x>=5)
  {y = 3*x}
}
x = seq(-10,10,by = 0.5)
y = R_testf(x)
plot(y)
y
```



 



```{r}
y = c(70,67,55,52,51,52,51,60,64)
x = c(1616.3,1610.9,1440.0,1400.7,1423.3,1471.3,1421.8,1547.1,1533.0)
lm(y~x)
```

```{r}
#2.3
z = c(10.4,10.6,10.1,10.4,10.5,10.3,10.3,10.2,10.9,10.6,10.8,
      10.5,10.9,10.6,10.8,10.5,10.7,10.2,10.7)
sd(z)
summary(z)
test1 = shapiro.test(z)
test1
t.test(z)

```

```{r}
x1=rnorm(20,19,4)
x2=rnorm(20,19,4)
x3=rnorm(20,19,4)
#+++++++++++++++++++++++++++++++++++++++++++
y1=x1^2+5
y2=x2^2+5
y3=x3^2+5

t=seq(1,20)
layout(matrix(c(1,1,2,3),2,2))
plot(t,y1,type='l',main='RAND_1')
plot(t,y2,main='RAND_2')
barplot(t,y3,main='RAND_3')

```

```{r}
 #定义log-likelihood函数
 LL<-function(params,data)
{#参数"params"是一个向量，依次包含了五个参数：p,mu1,sigma1,
 #mu2,sigma2.
 #参数"data"，是观测数据。
 t1<-dnorm(data,params[2],params[3])
 #这里的dnorm()函数是用来生成正态密度函数的。

 #log-likelihood函数
 return(-ll)
 #nlminb()函数是最小化一个函数的值，但我们是要最大化log-
 #likeilhood函数，所以需要在“ll”前加个“-”号。
 }
#3.2. 参数估计
 #用hist函数找出初始值
 hist(waiting,freq=F)
 lines(density(waiting))
 #拟合函数####optim####
 geyser.res<-nlminb(c(0.5,50,10,80,10),LL,data=waiting,
 lower=c(0.0001,-Inf,0.0001,-Inf,-Inf,0.0001),
 upper=c(0.9999,Inf,Inf,Inf,Inf))
 #LL是被最小化的函数。
 #data是拟合用的数据
 #lower和upper分别指定参数的上界和下界。
 
 
#3.3. 估计结果
#查看拟合的参数
 geyser.res$par

X<-seq(40,120,length=100)
 #读出估计的参数
 p<-geyser.res$par[1]
 mu1<-geyser.res$par[2]
 sig1<-geyser.res$par[3]
 mu2<-geyser.res$par[4]
 sig2<-geyser.res$par[5]
#将估计的参数函数代入原密度函数。
 f<-p*dnorm(X,mu1,sig1)+(1-p)*dnorm(X,mu2,sig2)


```


